title: Aperture Leatherworks
description: Exclusively Handmade in England
url: "https://www.apertureleatherworks.co.uk"  # Replace with your website URL
baseurl: ""  # Leave it as an empty string for the root URL
markdown: kramdown
theme: jekyll-theme-slate
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"

# Defaults for content
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins and assets
plugins:
  - jekyll-feed
  - jekyll-seo-tag
