title: Aperture Leatherworks
description: "Exclusively Handmade Leather Goods"
baseurl: ""
url: "https://www.apertureleatherworks.co.uk"
markdown: kramdown
theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag

# Ensure Jekyll doesn't treat the "products" folder as a collection or anything else
exclude:
  - README.md
  - LICENSE