title: Aperture Leatherworks
email: info@apertureleatherworks.co.uk
description: Exclusively Handmade in England
baseurl: "" # Keep empty if the site is at the root
url: "https://www.apertureleatherworks.co.uk" # Your live domain
theme: jekyll-theme-cayman # You can choose a Jekyll theme that suits your needs
collections:
  products:
    output: true
