title: Aperture Leatherworks
description: "Exclusively Handmade Leather Goods"
url: "https://apertureleatherworks.github.io"
baseurl: "/aperture-leatherworks"  # The subfolder your site is hosted in
markdown: kramdown
theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag

# Ensure Jekyll doesn't treat the "products" folder as a collection or anything else
exclude:
  - README.md
  - LICENSE
  - assets/css
  - assets/images