title: "Aperture Leatherworks"
baseurl: ""  # Leave empty if your site is at the root (not in a subfolder)
url: "https://apertureleatherworks.github.io"  # This is your GitHub Pages URL
baseurl: "/aperture-leatherworks"  # For a subfolder-based GitHub Pages site
