title: Aperture Leatherworks
description: Exclusively Handmade in England
url: "https://apertureleatherworks.github.io"
baseurl: "/aperture-leatherworks"
theme: jekyll-theme-minimal  # You can use another theme or create your own